# Dependencies
markdown:         rdiscount
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            MyBlog
tagline:          '有梦想，放手去追！'
description:      '欢迎大家来到我的个人博客'
url:              http://shelldone.com

author:
  name:           '166yuan'
  url:            https://github.com/166yuan

paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : soohu
